### ISSUE TITLE
Can I skip MIC validation?

### ISSUE THREAD

**Issue by hylowaker** [brocaar/chirpstack-network-server#514]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## Summary

I'm looking for feature that can disable MIC check.
I'm not sure it is implemented or not but I couldn't find any configuration about it.

## What is the use-case?

For debugging purpose.

## Implementation description

Just return the first session from session list for matching DevAddr, regardless of session key and MIC.

## Can you implement this by yourself and make a pull request?

Maybe like this?

```go
// internal/uplink/data/data.go
func getDeviceSessionForPHYPayload(ctx *dataContext) error {
	/** ... **/

	ds, err := storage.GetDeviceSessionForPHYPayload(ctx.ctx, storage.RedisPool(), ctx.RXPacket.PHYPayload, ctx.RXPacket.DR, txCh)

	disableMICValidation := true // read from configuration...
	if err == storage.ErrInvalidMIC && disableMICValidation {
		ctx.DeviceSession = ds
		return nil
	}

	if err != nil {
		returnErr := errors.Wrap(err, "get device-session error")

		// Forward error notification to the AS for debugging purpose.
		/** ... **/

		return returnErr
	}

	ctx.DeviceSession = ds
	return nil
}
```

**Comment by brocaar** [comment]
You can not. In a network with many devices, it is very likely that two devices (different DevEUIs) share the same DevAddr. This is because the DevEUI space is larger than the DevAddr space.

ChirpStack handles this by storing a DevAddr key with as value a list of DevEUIs. On uplink, ChirpStack will iterate over the different DevEUIs and validate the MIC using each network session-key. Thus, the MIC check is required to resolve a DevAddr to the correct DevEUI.
