### ISSUE TITLE
Latest Docker Image failed

### ISSUE THREAD

**Issue by BaerSy** [brocaar/chirpstack-network-server#535]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
I found the latest docker images is "Failed". Not sure if it's failed due to image build. Not sure if I can install it without errors.

![image](https://user-images.githubusercontent.com/27965673/121792888-45cea380-cbc8-11eb-960f-21aa3aecd1b9.png)

## What did you expect?
Docker Image "Passed"

## Steps to reproduce this issue

Steps:

1.
2.
3.
4.

## Could you share your log output?

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | Latest  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
You are referring to the CI status batch for the master branch. It is expected that there are failures as we do make mistakes now and then which will break the build. But no worries, this is not for the actual releases, which are also tested but must pass first in order to build the release artifacts.
